<?xml version="1.0"?>
<package format="3">
  <name>workshop_description</name>
  <version>0.0.0</version>
  <description>Description package for the ROSCon 2026 workshop</description>
  <maintainer email="bence.magyar.robotics@gmail.com">Bence Magyar</maintainer>
  <maintainer email="denis.stogl@stoglrobotics.de">Dr. Denis Štogl</maintainer>

  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ros2_control_demo_description</depend>
  <depend>workshop_hardware</depend>
  <depend>xacro</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
